name: Build and Publish DLLs

on:
  push:
    branches:
      - develop
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: windows-latest

    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Extract version digits from tag
        id: extract_version
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/refs\/tags\/v//')" >> $GITHUB_STATE

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Build DLLs
        run: dotnet build -c Release

      - name: Pack NuGet package
        run: dotnet pack .\castledice-game-logic\castledice-game-logic.csproj -c Release /p:PackageVersion=${{ env.VERSION }}

      - name: Publish DLLs to GitHub Packages
        run: dotnet nuget push D:\a\castledice-game-logic\castledice-game-logic\castledice-game-logic\bin\Release\castledice-game-logic.${{ env.VERSION }}.nupkg --source "https://nuget.pkg.github.com/OSTOLEX-Technologies/index.json" --api-key ${{ secrets.GH_PAT_PACK }}
