name: Build and Publish DLLs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Extract version digits from tag
        id: extract_version
        run: |
          $TAG="${{ github.ref_name }}"
          if (-not ($TAG -match '^v\d+\.\d+\.\d+(\w*)$')) {
            echo "Invalid tag format: $TAG"
            exit 1
          }
          $version=$TAG.Substring(1)
          echo "VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Build DLLs
        run: dotnet build -c Release

      - name: Pack NuGet package
        run: dotnet pack .\castledice-game-logic\castledice-game-logic.csproj -c Release /p:PackageVersion=${{ env.VERSION }}

      - name: Publish DLLs to GitHub Packages
        run: dotnet nuget push D:\a\castledice-game-logic\castledice-game-logic\castledice-game-logic\bin\Release\castledice-game-logic.${{ env.VERSION }}.nupkg --source "https://nuget.pkg.github.com/OSTOLEX-Technologies/index.json" --api-key ${{ secrets.GH_PAT_PACK }}
